### PR TITLE
Started on AU holidays

### PR DESCRIPTION
**Pull request by samwilson**
This is a start on adding Australian public holidays to this library.

### CODE REVIEW

**Comment by BenjaminPaap** [comment]
Great @samwilson, is this ready to get merged or do you need some more time? Just curious because you wrote "This is a start.."

**Comment by samwilson** [comment]
Yes, sorry I should've been clearer! :) I'm going to add the rest of the holidays as well. I sent this PR mainly just to check with you that it's going in the right direction.

I'll get some more done today.

**Comment by FlorianKoerner** [comment]
Status?

**Comment by samwilson** [comment]
Not finished :) but will hopefully get back to it. The requirement that we had for this package has become a lower priority. Sorry!

Have been working through the list here: https://en.wikipedia.org/wiki/Public_holidays_in_Australia#Public_holidays

**Pull request closed without merging**
