### PR TITLE
[BUGFIX] Mark national holidays as state-holidays as well

### PR DESCRIPTION
**Pull request by JostBaron**
If a holiday is a national holiday and it was requested if this day is a holiday in a specific state, the library would indicate "no, it is not a holiday".

### CODE REVIEW

**Comment by FlorianKoerner** [comment]
Do you have an example? Provider and date?

**Comment by JostBaron** [comment]
Yes, provider germany, dates are 25. and 26. December 2015

**Comment by FlorianKoerner** [comment]
You're right. Thanks for the note.

Can you take a look on the failed travis-ci check?
I'm going to accept this pull request if all checks run again.

**Comment by JostBaron** [comment]
Fixed.

**Comment by BenjaminPaap** [comment]
:+1: thanks for your work

**Pull request merged**
