### PR TITLE
Create BR Provider

### PR DESCRIPTION
**Pull request by wandersonwhcr**
This PR creates a Brazilian Holiday Provider with all holidays, nationals or state. Brazil have a problem: some holidays are optionals, it means that some people must work or not, depending of working nature. For example, Carnival ("Carnaval" in Brazilian Portuguese) is optional, but everyone don't work (crazy, huh?). I think we must add a static option to set if must use or not optional holidays.

~ brazilians like holidays hahahah ~

Cheers!

### CODE REVIEW

**Comment by FlorianKoerner** [comment]
Awesome work! Thank you!

**Comment by wandersonwhcr** [comment]
I forgot to add an entry into README. I will create another PR, sorry.

**Comment by FlorianKoerner** [comment]
Do you mean this?
https://github.com/checkdomain/Holiday/commit/a72d6be9fab775dc82a018d17366d44c7057265f#diff-04c6e90faac2675aa89e2176d2eec7d8R9

**Comment by wandersonwhcr** [comment]
Yes! TY :)

**Pull request merged**
