### PR TITLE
Add holidays for Reunion

### PR DESCRIPTION
**Pull request by julienmru**
Please consider merging this PR to add support for Reunion holidays

### CODE REVIEW

**Comment by wandersonwhcr** [comment]
Is this a province or state from France?

If yes, IMHO, we must create or change `FR` class and include a state parameter, like `BR` or `DE`.

**Comment by wandersonwhcr** [comment]
Examples:

https://github.com/checkdomain/Holiday/blob/master/src/Provider/BR.php
https://github.com/checkdomain/Holiday/blob/master/src/Provider/DE.php

**Comment by julienmru** [comment]
Dear @wandersonwhcr, it is an overseas territory, a part of France but with its own ISO country code, IDD, domain name extension, etc. It's located West coast of Madagascar.

When you ship to Reunion from other countries, you need to specify 'Reunion' as a country and not 'France'.

So I guess it's really up to your policy but most libraries handle Reunion as a specific country, eg. [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php).

**Comment by wandersonwhcr** [comment]
@julienmru TY

**Pull request merged**
