### PR TITLE
Update Autoload

### PR DESCRIPTION
**Pull request by wandersonwhcr**
This PR updates directory structure, changing autoloader from deprecated PSR-0 to PSR-4

### CODE REVIEW

**Comment by wandersonwhcr** [comment]
I didn't undestand Travis result. Can you rebuild f520a31 commit?

**Comment by FlorianKoerner** [comment]
You forgot https://github.com/checkdomain/Holiday/blob/master/.travis.yml#L10

**Comment by wandersonwhcr** [comment]
@FlorianKoerner I amend last commit (check f520a31) and Travis didn't build it. Any idea?

**Comment by wandersonwhcr** [comment]
Please don't merge this PR. I forgot to update `README.md` again.

**Comment by wandersonwhcr** [comment]
Damn. I understood the problem: I think I don't force my "git pull" command (I was tired). I'll check it at home.

**Comment by wandersonwhcr** [comment]
Done.

**Comment by wandersonwhcr** [comment]
See slimphp/Slim#2185.

**Comment by wandersonwhcr** [comment]
PHPUnit was never executing as needed with PHP `7.*`.

Done.

**Comment by FlorianKoerner** [comment]
Awesome work. Thank you!

**Pull request merged**
