### PR TITLE
Portugal Holidays

### PR DESCRIPTION
**Pull request by Danubio**
The holidays listed are for the year 2017. We (Portuguese) disabled a few a couple of years back and we are re-enabling them little by little

### CODE REVIEW

**Comment by FlorianKoerner** [comment]
Looks good. Would you adding some tests?
https://github.com/checkdomain/Holiday/tree/master/tests/Checkdomain/Holiday/Provider

**Comment by FlorianKoerner** [comment]
And could you please add support for 2013 - 2016?
See Example: https://github.com/jareis/Holiday/blob/master/lib/Checkdomain/Holiday/Provider/PT.php#L59

**Comment by Danubio** [comment]
Yes sure

**Comment by Danubio** [comment]
All done

**Comment by FlorianKoerner** [comment]
Thank you! 👍

**Pull request merged**
